services:
  mysql:
    image: mysql:8.0
    container_name: studentms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: studentms
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7
    container_name: studentms-redis
    restart: always
    ports:
      - "6380:6379"

  studentms-app-1:
    build: .
    container_name: studentms-app-1
    restart: always
    depends_on:
      - mysql
      - redis

  studentms-app-2:
    build: .
    container_name: studentms-app-2
    restart: always
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:latest
    container_name: studentms-nginx
    restart: always
    depends_on:
      - studentms-app-1
      - studentms-app-2
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  mysql_data: